FarmaciasGuadalajara/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FarmaciasGuadalajara.Models;
using FarmaciasGuadalajara.AppObjects;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using System.Net;
using System.Web.Security;
using System.Text.RegularExpressions;

namespace FarmaciasGuadalajara.Controllers
{
    public class MainController : Controller
    {
        FGEntities db = new FGEntities();
        cs_Client cl = new cs_Client();

        // GET: Main
        public ActionResult Index()
        {
            ViewBag.Menu = null;
            ViewBag.Result = null;
            ViewBag.winners = null;

            ////////var url = new ObjURL().getURLData(Request.Url.ToString());
            ////////var beforTable = "<p><b>Jorge Marquez Juarez</b>, agradecemos tu preferencia.</p>";
            ////////var Html1 = "<img src='" + url.UrlImage + @"/img/fondoEmail.png'>";

            ////////new cs_Email("noreply@kelloggs.com", "Kellogg’s® Cumple tus deseos Navideños", "jorgejamj@gmail.com", "", "Kellogg’s® Cumple tus deseos Navideños - Jorge Marquez Juarez", Html1, true, new ObjURL().getURLData(Request.Url.ToString()), beforTable).sendMail();

            var dummy = new cs_Client().getId();
            var dummyx = "";
            try {
                var configuration = new cs_Configuration();
                ViewBag.Menu = getMenu();
                ViewBag.Result = configuration;
                ViewBag.Analytics = configuration.Analytics;

                if (configuration.status == 3) {

                    var a = db.sp_ticketResultWinners(15,1).ToList();

                    ViewBag.winners = db.sp_ticketResultWinners(15, 1).ToList();
                }
                return View();
            } catch (Exception ex) {
                return View();
            }
        }

        public ActionResult Register() {
            ViewBag.Menu = null;
            ViewBag.Result = null;

            try {
                if (new cs_Client().getId() > 0) {
                    return RedirectToAction("Index");
                }
                var configuration = new cs_Configuration();
                ViewBag.Menu = getMenu();
                ViewBag.Result = configuration;
                ViewBag.Analytics = configuration.Analytics;
                ViewBag.ShowAnalytics = configuration.ShowAnalytics;

                return View();
            } catch (Exception ex) {
                return View();
            }
        }

        
        public ActionResult Gracias() {
            ViewBag.Menu = null;
            ViewBag.Result = null;

            try {
                //if (new cs_Client().getId() > 0) {
                //    return RedirectToAction("Index");
                //}
                var configuration = new cs_Configuration();
                ViewBag.Menu = getMenu();
                ViewBag.Result = configuration;

                return View();
            } catch (Exception ex) {
                return View();
            }
        }

        public ActionResult profile() {

            try {
                var ClientId = new cs_Client().getId();
                ViewBag.Menu = getMenu();
                if (ClientId == 0) {
                    return RedirectToAction("Index");
                }

                var a = db.sp_ticketResultClient(Convert.ToInt32(ClientId)).ToList();

                return View(db.sp_ticketResultClient(Convert.ToInt32(ClientId)).ToList());
            } catch (Exception ex) {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public string profileTickt(Int32 ticketId) {
            Session["TicketId"] = ticketId;
            return "Ok";
        }

        public ActionResult ChristmasTest() {

            try {
                if (new cs_Client().getId() == 0) {
                    return RedirectToAction("Index");
                }

                ViewBag.getState = getState();
                ViewBag.InitQuestion = null;
                //var InitQuestion = null;
                
                if (Session["TicketId"] != null) {
                    Tbl_Ticket tk = new Tbl_Ticket();
                    tk.TicketId = Convert.ToInt32(Session["TicketId"]);
                    db.sp_ticketCRUD("IT", tk.TicketId, Convert.ToInt32(new cs_Client().getId()),"", 0, 0, 1).First();
                    ViewBag.InitQuestion = JsonConvert.DeserializeObject<QuestionElement>(((sp_ticketCRUD_Result)ticketProcess(tk, "R").Data).message.ToString());
                } else {
                    var ticketPendiente = db.sp_getTicketPending(Convert.ToInt32(new cs_Client().getId())).First();
                    if (ticketPendiente.ToString() != "0") {
                        var tick = new Tbl_Ticket();
                        tick.TicketId = Convert.ToInt32(ticketPendiente);
                        ViewBag.InitQuestion = JsonConvert.DeserializeObject<QuestionElement>(((sp_ticketCRUD_Result)ticketProcess(tick, "R").Data).message.ToString());
                    }
                }

                ViewBag.Menu = getMenu();

                return View();
            } catch (Exception ex) {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Award() {

            //if (new Client().getId() == 0) {
            //    return RedirectToAction("Index");
            //}

            ViewBag.Menu = getMenu();
            return View();

        }

        public ActionResult Winners() {

            //if (new Client().getId() == 0) {
            //    return RedirectToAction("Index");
            //}

            ViewBag.Menu = getMenu();
            return View();

        }

        //*************** GET OPTIONS OF MENU
        public string getMenu() {
            var menu = new Menu(0).menu;
            try {
                if (new cs_Client().getId() > 0) {
                    menu = "";
                    menu = new Menu(1).menu;
                }
            } catch (Exception es) { }
            return menu;
        }

        //*************** SHOW MODAL
        [HttpPost]
        public ActionResult popData(string option) {
            try {
                ViewBag.data = option;
                return View();
            } catch (Exception ex) {
                return View();
            }
        }
        
        static string validatePass(string strIn) {
            // Replace invalid characters with empty strings.
            try {
                return Regex.Replace(strIn, @"[^\w\$@$!%*._]", "", RegexOptions.None, TimeSpan.FromSeconds(1.5));
            }
            // If we timeout when replacing invalid characters, 
            // we should return Empty.
            catch (RegexMatchTimeoutException) {
                return String.Empty;
            }

        }

        static bool validateEmail(string strIn) {
            // Replace invalid characters with empty strings.
            try {
                Regex Val = new Regex(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*");
                if (Val.IsMatch(strIn)) {
                    return true;
                }
                return false;
            }
            // If we timeout when replacing invalid characters, 
            // we should return Empty.
            catch (RegexMatchTimeoutException) {
                return false;
            }

        }

        //**************** CUSTOMER PROCESS (CRUD)
        [HttpPost]
        public JsonResult customerProcess(Cat_Client client, string option) {
            try {
                
                var errors = "";
                var email = "";
                var pass = "";
                var ladaPhone = "";
                var phone = "";
                var rnd = new GeneradorPassword();
                    rnd.LongitudPassword = 16;
                    rnd.PorcentajeMayusculas = 25;
                    rnd.PorcentajeNumeros = 25;
                    rnd.PorcentajeSimbolos = 25;
                    rnd.GetNewPassword();
                var newPass = rnd.GetNewPassword().ToString();

                switch (option) {
                    case "C":
                        if (!validateEmail(client.Email)) {
                            errors = errors + "<p>Formato invalido para el campo <b>Email</b></p>";
                        }
                        if (validatePass(client.Password) != client.Password) {
                            errors = errors + "<p>La contraseña debe tener al entre <b>8</b> y <b>16</b> caracteres</p> <p>Al menos un dígito, al menos una minúscula y al menos una mayúscula.</p> <p>Símbolos permitidos <b>$@!% *._</b>.</p><p>Ejemplo: <b>M1c0ntr@señ4.01</b></p>";
                        }
                        email = SimpleEncryption.Encrypt(client.Email, "FG");
                        pass = SimpleEncryption.Encrypt(client.Password, "FG");
                        ladaPhone = SimpleEncryption.Encrypt(client.LadaPhone, "FG");
                        phone = SimpleEncryption.Encrypt(client.Phone, "FG");
                        break;
                    case "R":
                        if (!validateEmail(client.Email)) {
                            errors = errors + "<p>Formato invalido para el campo <b>Email</b></p>";
                        }
                        if (validatePass(client.Password) != client.Password) {
                            errors = errors + "<p>La contraseña debe tener al entre <b>8</b> y <b>16</b> caracteres</p> <p>Al menos un dígito, al menos una minúscula y al menos una mayúscula.</p> <p>Símbolos permitidos <b>$@!% *._</b>.</p><p>Ejemplo: <b>M1c0ntr@señ4.01</b></p>";
                        }
                        email = SimpleEncryption.Encrypt(client.Email, "FG");
                        pass = SimpleEncryption.Encrypt(client.Password, "FG");
                        break;

FarmaciasGuadalajara/Views/Main/Award.cshtml
@{
    ViewBag.Title = "Award";
    Layout = "~/Views/Shared/_Layout_Index.cshtml";
}

<div class="content">
    <div class="content__section aligner" style="background-color:lightseagreen;">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h2>Premios</h2>
                </div>
            </div>
        </div>
    </div>
</div>

FarmaciasGuadalajara/Views/Main/ChristmasTest.cshtml
@using FarmaciasGuadalajara.AppObjects;
@{
    ViewBag.Title = "christmasTest";
    Layout = "~/Views/Shared/_Layout_Index.cshtml";
}

@section Scripts {
    <script src="/Scripts/christmasTest.js"></script>
    @*@Scripts.Render("~/bundles/christmastest")*@
}

<div class="content__section aligner" id="xmastest">
    <div class="container">

        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3">
                <p class="hidden-xs">&nbsp;</p>
                <img class="img-responsive" src="~/img/home_01.png" />
            </div>
            <div class="col-xs-6 col-sm-offset-2 col-md-offset-3 text-right" id="xmastest__sect">
                @*<button class="img_btn visible-xs pull-right" id="menu_mobile">
                    <img class="" src="~/img/btn_menu.png" />
                </button>*@
                <div class="text-right" id="receipt3" style="clear: both; padding-top:1em;">
                    <h2 class="uppercase">Datos de tu cuenta</h2>
                    <h3><span  class="amarillo">¡No lo olvides!</span><br />Conserva tu ticket de compra</h3>
                </div>
            </div>
        </div>


        <div class="row" id="xmastest__ticket">

            @if( ViewBag.InitQuestion == null ) {

                <div class="col-xs-6 col-sm-4 col-md-3 text-center" id="receipt2">
                    <p class="bold white">¿Dónde localizar tus datos?</p>
                    <img class="img-responsive" src="~/img/ticket.jpg" />
                </div>

                <div class="col-xs-6 col-sm-4 col-md-3 text-left" id="Receipt">   
                    <div class="form-group">
                        <label for="State" class="form-control-label">Estado:</label>
                        <select class="form-control" id="State" name="State">
                            <option value="">-- Selecciona --</option>
                            @foreach( var data in (List<string>)ViewBag.getState ) {
                                <option value="@data">@data</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="Location" class="form-control-label">Localidad:</label>
                        <select class="form-control" id="Location" name="Location">
                            <option value="">-- Selecciona --</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="SucursalNumber" class="form-control-label">Sucursal:</label>
                        <select class="form-control" id="SucursalNumber" name="SucursalNumber">
                            <option value="">-- Selecciona --</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="Total" class="form-control-label">Monto en productos <span class="amarillo">Kellogg's<sup>&reg;</sup> y/o Pringles<sup>&reg;</sup>:</span></label>
                        <input type="number" class="form-control" id="Total" name="Total">
                    </div>
                    <div class="form-group">
                        <label for="SerialNumber" class="form-control-label">No. de ticket:</label>
                        <input type="text" class="form-control" id="SerialNumber" name="SerialNumber">
                    </div>
                </div>
            }

            @if (ViewBag.InitQuestion != null) {
                var data = (QuestionElement)ViewBag.InitQuestion;
                var a = data;
                <div class="col-xs-12 text-right triviakill">
                    <p class="white">Responde las preguntas <span class="amarillo">lo más rápido</span> que puedas.</p>
                </div>
                <div class="col-xs-12 trivia triviakill" id="Question">
                    <div class="question">                        
                        <b id="lblQuestioninit"><label style="color:#f8e71c;"> 1 de 5</label></b>
                        <p id="lblQuestion">@data.questionName</p>
                    </div>
                    <div class="answers" id="RbtAnswer">
                        @foreach( var element in data.data ) {
                            <div class="answer" id="@element.answerId" name="answerId" value="@element.answerId">
                                @element.answerName
                            </div>
                            @*<input type="radio" id="@element.answerId" name="answerId" value="@element.answerId">*@
                        }
                    </div>
                </div>

            }
            else {
                
                <div class="col-xs-12 trivia" id="Question">
                    <div class="question">
                        <p id="lblQuestion">&nbsp;</p>
                    </div>
                    <div class="answers" id="RbtAnswer"> </div>
                </div>
                
            }
        <!--
        </div>
        <div class="row">
        -->
            <div class="col-xs-7 col-xs-offset-0 col-sm-4 col-md-4 col-md-offset-2 text-center mt-1 mb-2 triviakill">
                <button class="snowless" value="siguiente" id="nextStep">Siguiente</button>
            </div>
        </div>
    </div>
</div>

FarmaciasGuadalajara/Views/Main/Gracias.cshtml
@using FarmaciasGuadalajara.AppObjects;
@using FarmaciasGuadalajara.Models;
@{
    ViewBag.Title = "Registro";
    Layout = "~/Views/Shared/_Layout_Index.cshtml";
    var UserName = new cs_Client().getName();

    var Menu = ViewBag.Menu;
    var result = (cs_Configuration)ViewBag.Result;
}

@section Scripts {
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script src="/Scripts/register.js"></script>
    @*@Scripts.Render( "~/bundles/register" )*@
}

<div class="content__section aligner" id="gracias">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3">
                <p class="hidden-xs">&nbsp;</p>
                <img class="img-responsive" src="~/img/home_01.png" />
            </div>
            <div class="col-xs-6 col-sm-offset-2 col-md-offset-3 text-right" id="gracias__sect">
                <button class="img_btn visible-xs pull-right" id="menu_mobile">
                    <img class="" src="~/img/btn_menu.png" />
                </button>
            </div>
        </div>
        <div class="row" id="gracias__h">
            <div class="col-xs-9 col-sm-8 col-md-7 col-lg-6 text-left white_on_white">
                <p class="fs-2 amarillo bold mb-0 uppercase">¡Bien hecho!</p>
                <p class="fs-2 bold">Recibimos <span class="amarillo">tus datos</span> satisfactoriamente. Ya puedes continuar con <span class="amarillo">tu participación.</span></p>
                <p class="hidden-xs">&nbsp;</p>
                <button class="snowless" onclick="window.location.href='@Url.Action("ChristmasTest", "Main")';return false;">Subir ticket</button>
            </div>
        </div>

    </div>
</div>

FarmaciasGuadalajara/Views/Main/Index.cshtml
@using FarmaciasGuadalajara.AppObjects;
@using FarmaciasGuadalajara.Models;
@using System.Runtime.Serialization;
@using System.Runtime.Serialization.Json;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Index.cshtml";
    var UserName = new cs_Client().getName();

    var Menu = ViewBag.Menu;
    var result = (cs_Configuration)ViewBag.Result;
    List<cs_Winners> winners = null;
    
}

@switch (result.status) {
    case 0:  //Error 404
        <div class="content__section aligner bgimg">
            @Html.Partial("Error");
        </div>
    break;

    case 1:  //Home screen
        @Html.Partial( "HomeSec" );
    break;

    case 2:
        <div>@result.message</div>
        break;

    case 3: //Pantalla de Ganadores
        winners = Json.Decode<List<cs_Winners>>(ViewBag.winners[0].message.ToString());
        <div class="content__section aligner" id="winners">
            <div class="container">

                <div class="row visible-xs">
                    <div class="col-xs-5">
                        <img class="img-responsive" src="~/img/home_01.png" />
                    </div>
                    <div class="col-xs-7 text-right">
                        <button class="img_btn visible-inline-xs" id="menu_mobile">
                            <img class="" src="~/img/btn_menu.png" />
                        </button>
                    </div>
                </div>

                <div class="row">
                    <div class="hidden-xs col-sm-6 col-sm-offset-0 col-md-4 col-md-offset-2">
                        <img class="img-responsive" src="~/img/home_01.png" style="width: 50%;" />
                        <img class="img-responsive mt-1" src="~/img/home_02.png" />
                        <img class="img-responsive" src="~/img/home_03.png" style="margin: -25% 0 0 -20%;" />
                    </div>
                    <div class="col-xs-12 col-sm-6 text-center" id="winners__sect">
                        <h2 class="amarillo"><em>¡Gracias a todos!</em></h2>
                        <h3>Éstos son los ganadores ¡Felicidades!</h3>
                        <table class="table_w">
                            <thead>
                                <tr>
                                    <th><!--Lugar-->&nbsp;</th>
                                    <th>Nombre</th>
                                    <th>Tiempo</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach (var winner in winners) {
                                <tr>
                                    <td>@winner.Lugar° </td>
                                    <td>@winner.Nombre </td>
                                    <td>@winner.Tiempo </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row visible-xs">
                    <div class="col-xs-8 col-xs-offset-2">
                        <img class="img-responsive mt-1" src="~/img/home_02.png" />
                        <img class="img-responsive" src="~/img/home_03.png" style="margin: -25% 0 0 -20%;" />
                    </div>
                </div>
            </div>
        </div>
        break;
}

FarmaciasGuadalajara/Views/Main/Winners.cshtml
@{
    ViewBag.Title = "Winners";
    Layout = "~/Views/Shared/_Layout_Index.cshtml";
}

    <div class="content__section aligner">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h2>Ganadores</h2>
                </div>
            </div>
        </div>
    </div>

FarmaciasGuadalajara/Views/Main/profile.cshtml
@model IEnumerable<FarmaciasGuadalajara.Models.sp_ticketResultClient_Result>
@using FarmaciasGuadalajara.AppObjects;
@{
    ViewBag.Title = "profile";
    Layout = "~/Views/Shared/_Layout_Index.cshtml";
    var UserName = new cs_Client().getName();
    var User = (FarmaciasGuadalajara.AppObjects.cs_Client)new cs_Client().getData();
}

<div class="content__section aligner" id="profile_page">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3">
                <p class="hidden-xs">&nbsp;</p>
                <img class="img-responsive" src="~/img/home_01.png" />
            </div>
            <div class="col-xs-6 col-sm-offset-2 text-right" id="profile__sect">
                <button class="img_btn visible-xs pull-right" id="menu_mobile">
                    <img class="" src="~/img/btn_menu.png" />
                </button>
                <div class="hidden-xs text-right">
                    <a class="yellowlink logOut" href="#">Cerrar sesión</a>

                    @*<button class="img_btn pull-right" style="display:inline-block;">
                        <img src="~/img/btn_profile_off.png" />
                    </button>*@

                    <button class="snowless hover2" onclick="window.location.href='@Url.Action( "Index", "Main" )';return false;">Ir al inicio</button>
                </div>
                <div class="text-right" style="clear: both; padding-top:1em;">
                    <h2 class="uppercase amarillo">@User.Name @User.LastName1 @User.LastName2</h2>
                    <h3 class="hidden-xs">@User.Email<br />@User.Phone</h3>
                </div>
            </div>
        </div>

        <div class="row"> @*id="xmastest__ticket"*@
            <div class="col-xs-12 visible-xs text-right">
                <h3>@User.Email<br />@User.Phone</h3>
            </div>
            <div class="col-xs-12 col-sm-4 text-left">

                <p class="white_on_white">Es muy importante que conserves tu ticket de compra, ya que si resultas ganador lo necesitarás para reclamar tu premio.</p>
                <p class="white_on_white">En caso de resultar ganador serás notificado vía correo electrónico.</p>
            </div>
            <div class="col-xs-12 col-sm-8">
                <table class="table_w hidden-xs">
                    <thead>
                        <tr>
                            <th>
                                @*@Html.DisplayNameFor( model => model.FechaRegistro )*@
                                Participación
                            </th>
                            <th>
                                @Html.DisplayNameFor( model => model.Folio )
                            </th>
                            <th>
                                @*@Html.DisplayNameFor( model => model.Total )*@
                                Monto
                            </th>
                            @*<th> @Html.DisplayNameFor( model => model.Aciertos ) </th>*@
                            <th>
                                @Html.DisplayNameFor( model => model.Tiempo )
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if( Model.Count() != 0 ) {
                                foreach( var item in Model ) {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor( modelItem => item.FechaRegistro )
                                        </td>
                                        <td>
                                            @Html.DisplayFor( modelItem => item.Folio )
                                        </td>
                                        <td>
                                            @Html.DisplayFor( modelItem => item.Total )
                                        </td>
                                        @*<td>
                                                @Html.DisplayFor( modelItem => item.Aciertos )
                                            </td>*@
                                        <td>
                                            @Html.DisplayFor( modelItem => item.Tiempo )
                                        </td>
                                        <td>
                                            @if( item.TicketId != 0 ) {
                                                <div onclick="initQuestions(@item.TicketId)">Iniciar</div>
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                            else {
                                <tr>
                                    <td class="text-center" colspan="5">
                                        No tienes participaciones registradas aún.
                                    </td>
                                </tr>
                            }
                        }
                        
                    </tbody>
                </table>
                <table class="table_w visible-xs">
                    <thead>
                        <tr>
                            <th colspan="2">Participaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if( Model.Count() != 0 ) {
                                foreach( var item in Model ) {
                                    <tr>
                                        <td>@Html.DisplayFor( modelItem => item.FechaRegistro )</td>
                                        <td>
                                            Folio: @Html.DisplayFor( modelItem => item.Folio )
                                        </td>
                                    </tr>
                                    <tr style="border-bottom: 1px solid white;">
                                        <td colspan="2">
                                            <table>
                                                <tr>
                                                    <td>
                                                        Monto <br />
                                                        @Html.DisplayFor( modelItem => item.Total )
                                                    </td>
                                                    <td>
                                                        Tiempo <br />
                                                        @Html.DisplayFor( modelItem => item.Tiempo )
                                                    </td>
                                                    <td>
                                                        @if( item.TicketId != 0 ) {
                                                            <div onclick="initQuestions(@item.TicketId)">Iniciar</div>
                                                        }
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                }
                            }
                            else {
                                <tr>
                                    <td class="text-center">
                                        <p class="white_on_white">No tienes participaciones registradas aún.</p>
                                    </td>
                                </tr>
                            }
                        }

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
@section Scripts {
    <script src="~/Scripts/profile.js"></script>
    @*@Scripts.Render( "~/bundles/profile" )*@
}